import Link from "next/link"; import {Phone,Star,KeyRound, Waves,CheckCircle2,Search} from "lucide-react"; import {locations,testimonials,BUSINESS} from "@/lib/data"; import {getPublishedApartments} from "@/lib/apartments"; import ApartmentCard from "@/components/ApartmentCard";
export const revalidate=60;
export default async function Home(){const apartments=await getPublishedApartments();return <><section className="pt-8 pb-16"><div className="container text-center"><div className="inline-flex items-center gap-3"><div className="w-14 h-14 rounded-full border-2 border-[#C9A24A] grid place-items-center text-2xl font-black text-[#0B2A6F]">F</div><div className="text-left"><div className="text-2xl font-black text-[#0B2A6F]">FOWAAH'S</div><div className="text-xs tracking-[.28em] text-[#C9A24A]">APARTMENTS</div></div></div><h1 className="section-title mt-7">FOWAAH'S APARTMENTS: <span>SIMPLY LUXURY LIVING</span></h1><p className="max-w-2xl mx-auto mt-3 muted">Find Your Perfect Luxury Choice. For Rent & Sale.</p><div className="hero-frame mt-8"><img src="https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1800&q=85" alt="Luxury modern apartment"/></div><div className="flex flex-wrap justify-center gap-3 mt-6"><Link className="btn btn-primary" href="/apartments">Browse Apartments</Link><a className="btn btn-outline" href={`tel:${BUSINESS.intl}`}><Phone size={17}/>Call {BUSINESS.phone}</a></div></div></section>
<section className="relative -mt-2"><div className="container"><form action="/apartments" className="card p-5 grid md:grid-cols-5 gap-3"><select name="city" className="select"><option value="">City</option><option>Accra</option><option>Kumasi</option><option>Cape Coast</option></select><select name="type" className="select"><option value="">Rent / Sale</option><option>Rent</option><option>Sale</option></select><select name="beds" className="select"><option value="">Bedrooms</option><option>1</option><option>2</option><option>3</option><option>4+</option></select><select name="max" className="select"><option value="">Max Budget</option><option value="5000">GH₵ 5,000</option><option value="8000">GH₵ 8,000</option><option value="10000">GH₵ 10,000</option></select><button className="btn btn-gold"><Search size={18}/>Search</button></form></div></section>
<section className="section"><div className="container"><h2 className="section-title">OUR <span>LOCATIONS</span></h2><div className="grid grid-3 mt-8">{locations.map(l=><Link key={l.city} href={`/apartments?city=${encodeURIComponent(l.city)}`} className="card group"><img src={l.image} className="w-full aspect-[4/3] object-cover group-hover:scale-[1.02] transition" alt={l.city}/><div className="p-5"><div className="w-12 h-12 -mt-10 relative rounded-full bg-[#C9A24A] text-[#081C4D] grid place-items-center text-xl border-4 border-white">{l.icon}</div><h3 className="font-black text-2xl text-[#0B2A6F] mt-3">{l.city}</h3><p className="muted">{l.desc}</p><p className="text-sm mt-2">{apartments.filter(a=>a.city===l.city).length} available examples</p></div></Link>)}</div></div></section>
<section className="section bg-white"><div className="container"><h2 className="section-title">FEATURED <span>APARTMENTS</span></h2><div className="grid md:grid-cols-2 xl:grid-cols-3 mt-8">{apartments.filter(a=>a.featured).map(a=><ApartmentCard a={a} key={a.id}/>)}</div></div></section>
<section className="section"><div className="container"><h2 className="section-title">WHY CHOOSE <span>FOWAAH'S</span></h2><div className="grid grid-3 mt-8">{[["Premium Locations","Handpicked neighbourhoods close to beaches, business districts, schools and heritage sites.",Star],["Quality Service","Responsive support, verified properties and professional viewings.",CheckCircle2],["Flexible Options","Rent or buy, short or long stays, and flexible terms.",KeyRound]].map(([t,d,I])=><div className="card p-7" key={t}><I className="text-[#C9A24A]" size={36}/><h3 className="font-black text-xl text-[#0B2A6F] mt-4">{t}</h3><p className="muted mt-2">{d}</p></div>)}</div></div></section>
<section className="section bg-[#0B2A6F] text-white"><div className="container"><h2 className="text-3xl font-black">HOW IT <span className="text-[#C9A24A]">WORKS</span></h2><div className="grid md:grid-cols-4 mt-8">{["Browse","Enquire","Schedule a Viewing","Move In"].map((x,i)=><div className="p-5 border-l border-[#C9A24A]" key={x}><div className="text-[#C9A24A] text-3xl font-black">0{i+1}</div><h3 className="font-black mt-2">{x}</h3></div>)}</div></div></section>
<section className="section"><div className="container"><h2 className="section-title">WHAT CLIENTS <span>SAY</span></h2><div className="grid grid-3 mt-8">{testimonials.map(t=><div className="card p-6" key={t.name}><div className="text-[#C9A24A]">{"★".repeat(t.stars)}</div><p className="mt-3">“{t.text}”</p><b className="block mt-5 text-[#0B2A6F]">{t.name} · {t.city}</b></div>)}</div></div></section>
<section className="bg-[#081C4D] text-white py-9"><div className="container flex flex-wrap justify-between items-center gap-5"><div><div className="text-[#C9A24A] font-black">CONTACT US</div><a className="text-2xl font-black" href={`tel:${BUSINESS.intl}`}>{BUSINESS.phone}</a></div><a className="btn btn-gold" href={BUSINESS.snapchat}>@2XFOWAAH</a></div></section></>}
